import { ROLES_USUARIO, Usuario } from "@interfaces";

export const usuariosMock: Usuario[] = [
  {
    id: 1,
    nombre: "Carlos",
    apellidos: "Gomez",
    matricula: "ADM001",
    password: "admin123",
    rol: ROLES_USUARIO.ADMIN,
  },
  {
    id: 2,
    nombre: "Ana",
    apellidos: "Pérez",
    matricula: "ALU002",
    password: "password1",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 3,
    nombre: "Luis",
    apellidos: "Hernández",
    matricula: "ALU003",
    password: "password2",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 4,
    nombre: "Marta",
    apellidos: "Martínez",
    matricula: "ALU004",
    password: "password3",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 5,
    nombre: "José",
    apellidos: "Rodríguez",
    matricula: "ALU005",
    password: "password4",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 6,
    nombre: "Lucía",
    apellidos: "García",
    matricula: "ALU006",
    password: "password5",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 7,
    nombre: "Javier",
    apellidos: "López",
    matricula: "ALU007",
    password: "password6",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 8,
    nombre: "Raquel",
    apellidos: "Sánchez",
    matricula: "ALU008",
    password: "password7",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 9,
    nombre: "David",
    apellidos: "González",
    matricula: "ALU009",
    password: "password8",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 10,
    nombre: "Elena",
    apellidos: "Fernández",
    matricula: "ALU010",
    password: "password9",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 11,
    nombre: "Pedro",
    apellidos: "Jiménez",
    matricula: "ALU011",
    password: "password10",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 12,
    nombre: "Sofía",
    apellidos: "Moreno",
    matricula: "ALU012",
    password: "password11",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 13,
    nombre: "Manuel",
    apellidos: "Ruiz",
    matricula: "ALU013",
    password: "password12",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 14,
    nombre: "Isabel",
    apellidos: "Álvarez",
    matricula: "ALU014",
    password: "password13",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
  {
    id: 15,
    nombre: "Antonio",
    apellidos: "Cruz",
    matricula: "ALU015",
    password: "password14",
    materias: [],
    rol: ROLES_USUARIO.ALUMNO,
  },
];
